import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/picprincipal.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';

import lightBulb from "../../public/images/svgs/heart.png";
import TransitionEffect from '@/components/TransitionEffect';

export default function Home() {
  return (
    <>
      <Head>
        <title>Natalie Te Amo</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <TransitionEffect />
      
     <main className= 'flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
         <div className="flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/3 md:w-full'>
              <Image src={profilePic} alt="Guik" className="w-full h-auto lg:hidden md:inline-block md:w-full" priority         
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"/>
            </div>
            <div className = 'w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>          
              <AnimatedText text="UM PEDACINHO DO MEU AMOR POR VOCÊ" className='!text-6xl !text-left
              xl:!text-5xl lg:!text-center md:!text-5xl sm:!text-3xl
              '/>
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs' >
                  Princesa, eu fiz isso para te mostrar só um pouquinho do que sinto por você. É difícil expressar em palavras o turbilhão de emoções que você desperta em mim. Cada gesto seu, cada olhar, me faz perceber o quanto você é especial. Esse sentimento que tenho por você é imenso e transborda em cada pedacinho do meu ser. Quero que saiba que esse é apenas um vislumbre do amor intenso que guardo em meu coração.

                    </p>
            </div>
         </div>
          </Layout>
        
          <div className='absolute right-8 bottom-8 inline-block w-24 md:hidden'>
            <Image src={lightBulb} alt="Guik" className='w-full h-auto'/>
          </div>
     </main>
    </>
  )
}
